# Generated by Django 5.2.4 on 2025-08-05 04:10

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.post_featured_path),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.post_thumbnail_path),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.post_image_path),
        ),
        migrations.AddField(
            model_name='postimage',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
