# Generated by Django 5.2.4 on 2025-08-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_featured_image_post_thumbnail_postimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image_type',
            field=models.CharField(choices=[('overview', 'Overview'), ('care', 'Care'), ('closeup', 'Closeup'), ('indoor', 'Indoor'), ('healthy', 'Healthy'), ('decor', 'Decor')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
