# Generated by Django 5.2.4 on 2025-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postimage_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
