# Generated by Django 5.2.4 on 2025-08-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_postimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
