# Generated by Django 5.2.4 on 2025-08-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
