# Generated by Django 5.2.4 on 2025-08-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postscheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='blooming_season',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('plants', 'Plants'), ('flowers', 'Flowers'), ('fruits', 'Fruits'), ('gardening', 'Gardening Tips'), ('care', 'Plant Care')], default='plants', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='destination_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='family',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='growth_rate',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='harvest_time',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='max_height',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sunlight_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='watering_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='alt_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_type',
            field=models.CharField(choices=[('overview', 'Overview'), ('care', 'Care'), ('closeup', 'Closeup'), ('indoor', 'Indoor'), ('healthy', 'Healthy'), ('decor', 'Decor')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
