# Generated by Django 5.2.4 on 2025-08-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_category_name_alter_contactmessage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='destination_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='family',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='scientific_name',
            field=models.TextField(blank=True),
        ),
    ]
