# Generated by Django 5.2.4 on 2025-08-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_country_alter_post_destination_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
