# Generated by Django 5.2.4 on 2025-08-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_featured_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='harvest_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
