# Generated by Django 5.2.4 on 2025-08-06 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_featured_image_alter_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postscheduler',
            options={'verbose_name': 'Post Scheduler', 'verbose_name_plural': 'Post Scheduler'},
        ),
        migrations.AddField(
            model_name='postscheduler',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postscheduler',
            name='last_run',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
